### ISSUE TITLE
Slow deserialization

### ISSUE THREAD

**Issue by kyomster** [Ten0/serde_avro_fast#12] opened 2024-02-05 15:23 UTC
Hi,
I'm trying to unserialize a OCF avro compressed with ZStandard, using Golang or Java it takes about 300ms for one object, but in Rust using serde_avro_fast or the avro_rs it takes more than 1.5seconds.

Here is the code I'm using:
`
let mut reader = serde_avro_fast::object_container_file_encoding::Reader::from_slice(&delivery.data[..]).unwrap();
let res: Option<MyObject> = reader.deserialize_next_borrowed::<MyObject>().unwrap();
`

Is there something I am missing?

Thanks.

**Comment by Ten0** [comment] 2024-02-05 15:41
Hello, I'd like to investigate this but I'm not sure how since I don't have the relevant object.
Could you provide either:
- The object container file that takes a lot of time to deserialize along with the declaration of the `MyObject` struct(s) you're deserializing to
- A `perf` profiler dump of the decompression of that object (which I would otherwise do myself if provided with an object)

To obtain a `perf` profiler dump:
Cargo.toml
```toml
[profile.release]
debug = 2
```
Shell:
```bash
RUSTFLAGS="-C force-frame-pointers=yes" cargo build --release
perf record --call-graph dwarf -g -F999 target/release/foo # does the recording
perf script -F +pid > ./perf.perf # perf.perf can be opened by https://profiler.firefox.com/ -> flamegraphs
perf report # enter then enter again (annotate) -> precise assembly/rust mapping with sample heat
```
(I'm mostly interested by the `perf.perf` file)

Thanks! 🙂

Side note: `deserialize_next_borrowed` won't work if there is compression  (since the decompressed slice is temporary) - prefer using `deserialize_next` to have typechecking that you're not deserializing in e.g. an `&str`.

**Comment by kyomster** [comment] 2024-02-06 08:48
You'll find the OCF and the avro schema in the file attached.

I tried with 0.4.1 and 1.0.0-rc4 with the same result.

Thank you very much.
[data.zip](https://github.com/Ten0/serde_avro_fast/files/14176981/data.zip)

**Comment by Ten0** [comment] 2024-02-06 08:50
Can you please also provide the rust structs?

**Comment by kyomster** [comment] 2024-02-06 09:00
Here it is. Generated using rsgen-avro.

[avro.zip](https://github.com/Ten0/serde_avro_fast/files/14177150/avro.zip)

**Comment by Ten0** [comment] 2024-02-17 21:14
I cannot reproduce: with `serde_avro_fast = { version = "1.0.0-rc.4", features = ["zstandard"] }`, with the following code:
```rust
mod schema;

fn main() {
	let file_content = std::fs::read("avro.bin").unwrap();
	let start = std::time::Instant::now();
	let mut reader =
		serde_avro_fast::object_container_file_encoding::Reader::from_slice(&file_content).unwrap();
	let count = reader
		.deserialize::<schema::GatewayTsValue>()
		.map(|e| e.expect("failed to deserialize"))
		.count();
	let elapsed = start.elapsed();
	dbg!(elapsed, count, elapsed / count as u32);
}
```
and what you provided as schema, I get the following output from a `cargo run --release`:
```
[src/main.rs:13] elapsed = 184.897008ms
[src/main.rs:13] count = 1
[src/main.rs:13] elapsed / count as u32 = 184.897008ms
```

Looking at the `perf` benchmark, the only thing that seemed slightly shocking was the amount of time that would be spent in `read_varint`:
![image](https://github.com/Ten0/serde_avro_fast/assets/9094255/e853140e-28ad-4668-b2ba-a1d80db82253)

So I've optimized that in 0b7f502d6d1c8b71598188fff41bdfe543d7e2c9 and now I've got:
```
[src/main.rs:13] elapsed = 158.625694ms
[src/main.rs:13] count = 1
[src/main.rs:13] elapsed / count as u32 = 158.625694ms
```

and

![image](https://github.com/Ten0/serde_avro_fast/assets/9094255/3840f8a2-bccd-40c4-afe8-6f9c1f21e700)

Anyway that was detail - I suspect your issue may be lying elsewhere. (e.g if I run it without `--release`, it takes ~650ms on my computer, which is closer to the 1.5s you were talking about)
Can you try running the code I provided locally with `cargo run --release` and see if you still have the >1.5s/run ?

**Comment by Ten0** [comment] 2024-03-10 23:22
closing because can't reproduce and no news from author

**Closed by Ten0** 2024-03-10 23:22 UTC
Labels: Waiting on issue author
