### ISSUE TITLE
LogicalType issue or user error?

### ISSUE THREAD

**Issue by tghunt** [Ten0/serde_avro_fast#26] opened 2024-11-23 00:27 UTC
Hello all,

I have an apache-avro solution that I was looking to improve performance on and I found this.  Initial tests show huge speed improvements as noted in the documentation.

I am currently looking to resolve a discrepancy regarding logicalTypes for:

- {"name": "END_DATE", "type": {"logicalType": "date", "type": "int"}},
  - Example: 1632306
- {"name": "TIME_1", "type": "long", "logicalType":"timestamp"},
  - Example: 1732306924
- {"name": "TIME2", "type": "long", "logicalType":"timestamp-millis"},
  - Example: 1732306924000
- {"name": "TIME3", "type": "long", "logicalType":"timestamp-micros"},
  - Example: 1732306924000000

Using apache-avro when I extract the data using python or load into BQ, the values are represented in the appropriate DATE, TIMESTAMP formats.

However, when I use this crate is simply comes through as the raw value.  I had hoped to find something in the test cases, but I did not see any that tested timestamp related logicalTypes.

Any help would be greatly appreciated.

**Comment by Ten0** [comment] 2024-11-23 02:53
Hello and welcome! 
To deserialize timestamps via serde if you need actual date types from chrono or time instead of the raw timestamps, the most idiomatic and efficient way that I know of is via the serde_with crate. Either of the basic serde_with functions or their serde_as will work. I don't remember what value date gets though but I imagine something similar exists if they didn't pick something too random, or worse case scenario it should be reasonably easy to write the deserialize_with function for date that matches your desired output type.
Please let me know if that is unclear 🙂

**Comment by tghunt** [comment] 2024-11-23 17:40
The deserialization for validation is being done in python (local inspection) and loading into BigQuery.  Both of which should handle the conversion just fine.

I realized this morning that my BQ load attempt used the UI create table instead of using the SQL load command.  Using the SQL load command with:
`enable_logical_types=TRUE`
caused the date column to populate properly but not the timestamp columns.


Upon verifying this, I went back to comparing the schemas again and found the following:

The schema definition for END_DATE was: 
`{"name": "END_DATE", "type": {"logicalType": "date", "type": "int"}} `
which is understood by the deserialization methods in python and BigQuery, thus there is no issue here.

The schema definition for the time fields was of the form:
`{"name": "TIME1", "type": "long", "logicalType": "timestamp-micros"}`
which is where the issue seems to come from.

The apache_avro crate converts the user format to the following:
`{'name': 'TIME1', 'type': { 'logicalType': 'timestamp-micros', 'type': 'long'}} `

Whereas the serde_fast_avro maintains the original format that appears to be un-supported.


If I update the source schema to have this format: 
`{'name': 'TIME1', 'type': { 'logicalType': 'timestamp-micros', 'type': 'long'}}`,
 then my local python inspector and the big query load show the proper results.

I revisited the Avro spec and it is not immediately clear that when dealing with logicalTypes, the primary "type" key should be an object instead of a value 

Thus, the question now appears to be if the serde_fast_avro should support the schema modifications as the apache_avro does, or should the user be forced to find it on their own?


Thank you for your time and response, it led me to find the root cause issue.

**Comment by Ten0** [comment] 2024-11-23 21:02
It's unclear to me what you're trying to achieve. Are you using this crate to serialize or deserialize? Are you using the derive? Are you specifying the logical types in the derive? Which version are you using?

Can you please provide me with a code sample that showcases your issue, and tell me what it does and what you think it should/may do instead?

Thanks,

**Comment by tghunt** [comment] 2024-11-23 23:46
[serde_fast_zvro_issue.zip](https://github.com/user-attachments/files/17883129/serde_fast_zvro_issue.zip)

In the attached file you should see the Cargo.toml I am using as well as a sample main.rs which will generate a good and bad avro file.  By good implies the date and time are handled appropriately and bad is not.  The schema format in the bad is not supported/interpreted properly in the python code, nor is it handled properly when loading the avro file into BigQuery.  

Running the python code will provide you with the stored schemas for comparison as well as the date and time fields.

I am after the results from the good Avro file.  Please let me know if I can provide additional insights.

**Comment by Ten0** [comment] 2024-11-24 23:29
Ah so what you're saying is that this schema:
```
{
            "type": "record",
            "name": "Root",
            "fields": [
                {"name": "DATE", "logicalType": "date", "type": "int"},
```
ignores the `logicalType` field, and you'd rather maybe it didn't, and maybe it should instead "fix" the schema, serializing a version that actually respects the spec after?

The reason why this field is not taken into account is that having `logicalType` here instead of in `type` is not a syntax that should be interpreted according to the specification:
https://avro.apache.org/docs/++version++/specification/#schema-record
Indeed we can see that in `record`'s `fields` there's no mention of possibly having a `logicalType` attribute that would apply to the inner type, instead it is specified that `type` should be a `schema`, including nodes of the form `{"type": "int", "logicalType":"something"}` (as per [this](https://avro.apache.org/docs/++version++/specification/#logical-types) and [this](https://avro.apache.org/docs/++version++/specification/#schema-declaration)).

The rust `apache-avro` crate does not have a great history of respecting the established standards or specifications when it comes to schema generation and parsing ([AVRO-3925](https://issues.apache.org/jira/browse/AVRO-3925)...), so I'm not sure it should be taken as a role model here.

Our current implementation preserves the entirety of the schema attributes after parsing (doc, default...), we don't re-serialize it from the parsed form, so as to allow users to generate exactly the schema they want even if not all attributes are known by this crate, for potential use in other systems further down the line, so it would be heavy and lossy and weird to try to fix broken things in there (because we'd then have to parse and re-serialize, and we would leave mostly untouched but not all of it and we might break some things...).
It doesn't seem worth breaking this nice property that we just "leave the schema as is" just to support fixing incorrect schemas. I'd rather whatever tool wrote the incorrect schema gets fixed. (Or if it's a user mistake that they fix it.)

In fact more generally, trying to recover from mistakes (a.k.a silent failing) is generally bad, because it makes it significantly harder then to pinpoint the cause of bugs.
Take this for example: if apache-avro had failed to take these into account as you were writing the schemas, you'd immediately have noticed that this is not where logical types should have been written.
Instead because you had been using a silent-fail-recovery before, it sent you on a wrong track of thinking that your new tool didn't work correctly when parsing the same incorrect schema in there, which made your (and my) investigation significantly longer than if logical types of the incorrect schema just didn't ever work in any tool in the first place.
I wouldn't want to be the reason why somebody else loses more time having an incorrect schema that worked here not work in another avro-related tool than they would have spent fixing it right away...

Consequently I'm closing this, but feel free to continue the discussion if you're not convinced by the elements above or if you have new elements to bring to the table.

In any case, happy that you could find the issue and solve it! 😊

**Closed by Ten0** 2024-11-24 23:29 UTC

**Comment by tghunt** [comment] 2024-11-25 15:32
Thank you for your time and interaction on this.

I don't disagree with the approach and think including the correct format makes sense.
